#
# Makefile for building nufxlib as a DLL under Visual C++ (tested with 6.0).
#
# Run with "nmake /f Makefile.dll".
#
# To build without debugging info, use "nmake nodebug=1".
# To build with libz, use "nmake libz=1".
# To build with libbz2, use "nmake libbz2=1".
#
# Output is nufxlib.dll/nufxlib.lib for the "release" version, and
# nufxlibD.dll/nufxlibD.lib for the "debug" version.  It's important
# to keep this separate because the "debug" version links against
# msvcrtd.dll, which non-developer systems won't have.
#
# For libz/libbz2, you need to have the appropriate library either
# in this directory or in a standard location that the linker can find
#

CFG=nufxlib - Win32 Debug
MY_BUILD_FLAGS=/D "DEBUG_MSGS"
!ifdef NODEBUG
CFG=nufxlib - Win32 Release
MY_BUILD_FLAGS=
!endif

MY_LIB_FLAGS=
!ifdef LIBZ
MY_BUILD_FLAGS = $(MY_BUILD_FLAGS) /D "ENABLE_DEFLATE"
MY_LIB_FLAGS = zlib.lib $(MY_LIB_FLAGS)
!endif
!ifdef LIBBZ2
MY_BUILD_FLAGS = $(MY_BUILD_FLAGS) /D "ENABLE_BZIP2"
MY_LIB_FLAGS = libbz2.lib $(MY_LIB_FLAGS)
!endif


# Microsoft Developer Studio Generated NMAKE File, Based on nufxlib.dsp
!IF "$(CFG)" == ""
CFG=nufxlib - Win32 Debug
!MESSAGE No configuration specified. Defaulting to nufxlib - Win32 Debug.
!ENDIF 

!IF "$(CFG)" != "nufxlib - Win32 Release" && "$(CFG)" != "nufxlib - Win32 Debug"
!MESSAGE Invalid configuration "$(CFG)" specified.
!MESSAGE You can specify a configuration when running NMAKE
!MESSAGE by defining the macro CFG on the command line. For example:
!MESSAGE 
!MESSAGE NMAKE /f "nufxlib.mak" CFG="nufxlib - Win32 Debug"
!MESSAGE 
!MESSAGE Possible choices for configuration are:
!MESSAGE 
!MESSAGE "nufxlib - Win32 Release" (based on "Win32 (x86) Dynamic-Link Library")
!MESSAGE "nufxlib - Win32 Debug" (based on "Win32 (x86) Dynamic-Link Library")
!MESSAGE 
!ERROR An invalid configuration is specified.
!ENDIF 

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE 
NULL=nul
!ENDIF 

!IF  "$(CFG)" == "nufxlib - Win32 Release"

OUTDIR=.\Release
INTDIR=.\Release
# Begin Custom Macros
OutDir=.\Release
# End Custom Macros

ALL : "$(OUTDIR)\nufxlib.dll"

CLEAN :
	-@erase "$(INTDIR)\Archive.obj"
	-@erase "$(INTDIR)\ArchiveIO.obj"
	-@erase "$(INTDIR)\Bzip2.obj"
	-@erase "$(INTDIR)\Compress.obj"
	-@erase "$(INTDIR)\Crc16.obj"
	-@erase "$(INTDIR)\Debug.obj"
	-@erase "$(INTDIR)\Deferred.obj"
	-@erase "$(INTDIR)\Deflate.obj"
	-@erase "$(INTDIR)\Entry.obj"
	-@erase "$(INTDIR)\Expand.obj"
	-@erase "$(INTDIR)\FileIO.obj"
	-@erase "$(INTDIR)\Funnel.obj"
	-@erase "$(INTDIR)\Lzc.obj"
	-@erase "$(INTDIR)\Lzw.obj"
	-@erase "$(INTDIR)\MiscStuff.obj"
	-@erase "$(INTDIR)\MiscUtils.obj"
	-@erase "$(INTDIR)\Record.obj"
	-@erase "$(INTDIR)\SourceSink.obj"
	-@erase "$(INTDIR)\Squeeze.obj"
	-@erase "$(INTDIR)\Thread.obj"
	-@erase "$(INTDIR)\Value.obj"
	-@erase "$(INTDIR)\vc60.idb"
	-@erase "$(INTDIR)\Version.obj"
	-@erase "$(OUTDIR)\nufxlib.dll"
	-@erase "$(OUTDIR)\nufxlib.exp"
	-@erase "$(OUTDIR)\nufxlib.lib"
	-@erase "Version.c"

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

CPP=cl.exe
CPP_PROJ=/nologo /MD /W3 /GX /O2 /D "WIN32" /D "NDEBUG" /D "_WINDOWS" /D "_MBCS" /D "_USRDLL" /D "NUFXLIB_EXPORTS" /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c $(MY_BUILD_FLAGS)

.c{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.c{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

MTL=midl.exe
MTL_PROJ=/nologo /D "NDEBUG" /mktyplib203 /win32 
RSC=rc.exe
BSC32=bscmake.exe
BSC32_FLAGS=/nologo /o"$(OUTDIR)\nufxlib.bsc" 
BSC32_SBRS= \
	
LINK32=link.exe
LINK32_FLAGS=kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib $(MY_LIB_FLAGS) /nologo /dll /incremental:no /pdb:"$(OUTDIR)\nufxlib.pdb" /machine:I386 /out:"$(OUTDIR)\nufxlib.dll" /implib:"$(OUTDIR)\nufxlib.lib" 
LINK32_OBJS= \
	"$(INTDIR)\Archive.obj" \
	"$(INTDIR)\ArchiveIO.obj" \
	"$(INTDIR)\Bzip2.obj" \
	"$(INTDIR)\Compress.obj" \
	"$(INTDIR)\Crc16.obj" \
	"$(INTDIR)\Debug.obj" \
	"$(INTDIR)\Deferred.obj" \
	"$(INTDIR)\Deflate.obj" \
	"$(INTDIR)\Entry.obj" \
	"$(INTDIR)\Expand.obj" \
	"$(INTDIR)\FileIO.obj" \
	"$(INTDIR)\Funnel.obj" \
	"$(INTDIR)\Lzc.obj" \
	"$(INTDIR)\Lzw.obj" \
	"$(INTDIR)\MiscStuff.obj" \
	"$(INTDIR)\MiscUtils.obj" \
	"$(INTDIR)\Record.obj" \
	"$(INTDIR)\SourceSink.obj" \
	"$(INTDIR)\Squeeze.obj" \
	"$(INTDIR)\Thread.obj" \
	"$(INTDIR)\Value.obj" \
	"$(INTDIR)\Version.obj"

"$(OUTDIR)\nufxlib.dll" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

SOURCE="$(InputPath)"
DS_POSTBUILD_DEP=$(INTDIR)\postbld.dep

ALL : $(DS_POSTBUILD_DEP)

# Begin Custom Macros
OutDir=.\Release
# End Custom Macros

$(DS_POSTBUILD_DEP) : "$(OUTDIR)\nufxlib.dll"
   copy Release\nufxlib.dll .
	copy Release\nufxlib.lib .
	echo Helper for Post-build step > "$(DS_POSTBUILD_DEP)"

!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"

OUTDIR=.\Debug
INTDIR=.\Debug
# Begin Custom Macros
OutDir=.\Debug
# End Custom Macros

ALL : "$(OUTDIR)\nufxlibD.dll" "$(OUTDIR)\nufxlib.bsc"


CLEAN :
	-@erase "$(INTDIR)\Archive.obj"
	-@erase "$(INTDIR)\Archive.sbr"
	-@erase "$(INTDIR)\ArchiveIO.obj"
	-@erase "$(INTDIR)\ArchiveIO.sbr"
	-@erase "$(INTDIR)\Bzip2.obj"
	-@erase "$(INTDIR)\Bzip2.sbr"
	-@erase "$(INTDIR)\Compress.obj"
	-@erase "$(INTDIR)\Compress.sbr"
	-@erase "$(INTDIR)\Crc16.obj"
	-@erase "$(INTDIR)\Crc16.sbr"
	-@erase "$(INTDIR)\Debug.obj"
	-@erase "$(INTDIR)\Debug.sbr"
	-@erase "$(INTDIR)\Deferred.obj"
	-@erase "$(INTDIR)\Deferred.sbr"
	-@erase "$(INTDIR)\Deflate.obj"
	-@erase "$(INTDIR)\Deflate.sbr"
	-@erase "$(INTDIR)\Entry.obj"
	-@erase "$(INTDIR)\Entry.sbr"
	-@erase "$(INTDIR)\Expand.obj"
	-@erase "$(INTDIR)\Expand.sbr"
	-@erase "$(INTDIR)\FileIO.obj"
	-@erase "$(INTDIR)\FileIO.sbr"
	-@erase "$(INTDIR)\Funnel.obj"
	-@erase "$(INTDIR)\Funnel.sbr"
	-@erase "$(INTDIR)\Lzc.obj"
	-@erase "$(INTDIR)\Lzc.sbr"
	-@erase "$(INTDIR)\Lzw.obj"
	-@erase "$(INTDIR)\Lzw.sbr"
	-@erase "$(INTDIR)\MiscStuff.obj"
	-@erase "$(INTDIR)\MiscStuff.sbr"
	-@erase "$(INTDIR)\MiscUtils.obj"
	-@erase "$(INTDIR)\MiscUtils.sbr"
	-@erase "$(INTDIR)\Record.obj"
	-@erase "$(INTDIR)\Record.sbr"
	-@erase "$(INTDIR)\SourceSink.obj"
	-@erase "$(INTDIR)\SourceSink.sbr"
	-@erase "$(INTDIR)\Squeeze.obj"
	-@erase "$(INTDIR)\Squeeze.sbr"
	-@erase "$(INTDIR)\Thread.obj"
	-@erase "$(INTDIR)\Thread.sbr"
	-@erase "$(INTDIR)\Value.obj"
	-@erase "$(INTDIR)\Value.sbr"
	-@erase "$(INTDIR)\vc60.idb"
	-@erase "$(INTDIR)\vc60.pdb"
	-@erase "$(INTDIR)\Version.obj"
	-@erase "$(INTDIR)\Version.sbr"
	-@erase "$(OUTDIR)\nufxlib.bsc"
	-@erase "$(OUTDIR)\nufxlibD.dll"
	-@erase "$(OUTDIR)\nufxlib.exp"
	-@erase "$(OUTDIR)\nufxlib.ilk"
	-@erase "$(OUTDIR)\nufxlibD.lib"
	-@erase "$(OUTDIR)\nufxlib.pdb"
	-@erase "Version.c"

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

CPP=cl.exe
CPP_PROJ=/nologo /MDd /W3 /Gm /GX /ZI /Od /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /D "_MBCS" /D "_USRDLL" /D "NUFXLIB_EXPORTS" /FR"$(INTDIR)\\" /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /GZ /c $(MY_BUILD_FLAGS) 

.c{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.c{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

MTL=midl.exe
MTL_PROJ=/nologo /D "_DEBUG" /mktyplib203 /win32 
RSC=rc.exe
BSC32=bscmake.exe
BSC32_FLAGS=/nologo /o"$(OUTDIR)\nufxlib.bsc" 
BSC32_SBRS= \
	"$(INTDIR)\Archive.sbr" \
	"$(INTDIR)\ArchiveIO.sbr" \
	"$(INTDIR)\Bzip2.sbr" \
	"$(INTDIR)\Compress.sbr" \
	"$(INTDIR)\Crc16.sbr" \
	"$(INTDIR)\Debug.sbr" \
	"$(INTDIR)\Deferred.sbr" \
	"$(INTDIR)\Deflate.sbr" \
	"$(INTDIR)\Entry.sbr" \
	"$(INTDIR)\Expand.sbr" \
	"$(INTDIR)\FileIO.sbr" \
	"$(INTDIR)\Funnel.sbr" \
	"$(INTDIR)\Lzc.sbr" \
	"$(INTDIR)\Lzw.sbr" \
	"$(INTDIR)\MiscStuff.sbr" \
	"$(INTDIR)\MiscUtils.sbr" \
	"$(INTDIR)\Record.sbr" \
	"$(INTDIR)\SourceSink.sbr" \
	"$(INTDIR)\Squeeze.sbr" \
	"$(INTDIR)\Thread.sbr" \
	"$(INTDIR)\Value.sbr" \
	"$(INTDIR)\Version.sbr"

"$(OUTDIR)\nufxlib.bsc" : "$(OUTDIR)" $(BSC32_SBRS)
    $(BSC32) @<<
  $(BSC32_FLAGS) $(BSC32_SBRS)
<<

LINK32=link.exe
LINK32_FLAGS=kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib $(MY_LIB_FLAGS) /nologo /dll /incremental:yes /pdb:"$(OUTDIR)\nufxlib.pdb" /debug /machine:I386 /out:"$(OUTDIR)\nufxlibD.dll" /implib:"$(OUTDIR)\nufxlibD.lib" /pdbtype:sept 
LINK32_OBJS= \
	"$(INTDIR)\Archive.obj" \
	"$(INTDIR)\ArchiveIO.obj" \
	"$(INTDIR)\Bzip2.obj" \
	"$(INTDIR)\Compress.obj" \
	"$(INTDIR)\Crc16.obj" \
	"$(INTDIR)\Debug.obj" \
	"$(INTDIR)\Deferred.obj" \
	"$(INTDIR)\Deflate.obj" \
	"$(INTDIR)\Entry.obj" \
	"$(INTDIR)\Expand.obj" \
	"$(INTDIR)\FileIO.obj" \
	"$(INTDIR)\Funnel.obj" \
	"$(INTDIR)\Lzc.obj" \
	"$(INTDIR)\Lzw.obj" \
	"$(INTDIR)\MiscStuff.obj" \
	"$(INTDIR)\MiscUtils.obj" \
	"$(INTDIR)\Record.obj" \
	"$(INTDIR)\SourceSink.obj" \
	"$(INTDIR)\Squeeze.obj" \
	"$(INTDIR)\Thread.obj" \
	"$(INTDIR)\Value.obj" \
	"$(INTDIR)\Version.obj"

"$(OUTDIR)\nufxlibD.dll" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

SOURCE="$(InputPath)"
DS_POSTBUILD_DEP=$(INTDIR)\postbld.dep

ALL : $(DS_POSTBUILD_DEP)

# Begin Custom Macros
OutDir=.\Debug
# End Custom Macros

$(DS_POSTBUILD_DEP) : "$(OUTDIR)\nufxlibD.dll" "$(OUTDIR)\nufxlib.bsc"
   copy Debug\nufxlibD.dll .
	copy Debug\nufxlibD.lib .
	echo Helper for Post-build step > "$(DS_POSTBUILD_DEP)"

!ENDIF 


!IF "$(NO_EXTERNAL_DEPS)" != "1"
!IF EXISTS("nufxlib.dep")
!INCLUDE "nufxlib.dep"
!ELSE 
!MESSAGE Warning: cannot find "nufxlib.dep"
!ENDIF 
!ENDIF 


!IF "$(CFG)" == "nufxlib - Win32 Release" || "$(CFG)" == "nufxlib - Win32 Debug"
SOURCE="Archive.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Archive.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Archive.obj"	"$(INTDIR)\Archive.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="ArchiveIO.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\ArchiveIO.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\ArchiveIO.obj"	"$(INTDIR)\ArchiveIO.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Bzip2.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Bzip2.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Bzip2.obj"	"$(INTDIR)\Bzip2.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Compress.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Compress.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Compress.obj"	"$(INTDIR)\Compress.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Crc16.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Crc16.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Crc16.obj"	"$(INTDIR)\Crc16.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Debug.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Debug.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Debug.obj"	"$(INTDIR)\Debug.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Deferred.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Deferred.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Deferred.obj"	"$(INTDIR)\Deferred.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Deflate.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Deflate.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Deflate.obj"	"$(INTDIR)\Deflate.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Entry.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Entry.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Entry.obj"	"$(INTDIR)\Entry.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Expand.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Expand.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Expand.obj"	"$(INTDIR)\Expand.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="FileIO.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\FileIO.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\FileIO.obj"	"$(INTDIR)\FileIO.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Funnel.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Funnel.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Funnel.obj"	"$(INTDIR)\Funnel.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Lzc.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Lzc.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Lzc.obj"	"$(INTDIR)\Lzc.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Lzw.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Lzw.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Lzw.obj"	"$(INTDIR)\Lzw.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="MiscStuff.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\MiscStuff.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\MiscStuff.obj"	"$(INTDIR)\MiscStuff.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="MiscUtils.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\MiscUtils.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\MiscUtils.obj"	"$(INTDIR)\MiscUtils.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Record.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Record.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Record.obj"	"$(INTDIR)\Record.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="SourceSink.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\SourceSink.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\SourceSink.obj"	"$(INTDIR)\SourceSink.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Squeeze.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Squeeze.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Squeeze.obj"	"$(INTDIR)\Squeeze.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Thread.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Thread.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Thread.obj"	"$(INTDIR)\Thread.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Value.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Value.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Value.obj"	"$(INTDIR)\Value.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 

SOURCE="Version.c"

!IF  "$(CFG)" == "nufxlib - Win32 Release"


"$(INTDIR)\Version.obj" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "nufxlib - Win32 Debug"


"$(INTDIR)\Version.obj"	"$(INTDIR)\Version.sbr" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 


# this isn't great, but it'll have to do
SOURCE="Version.c.in"
Version.c: Version.c.in
	copy Version.c.in Version.c
	@echo -
	@echo - NOTE: you must update Version.c by hand
	@echo -

!ENDIF 

